"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
This is a base proto file for databroker and kuksa-val-basic
function set
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import types_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class EntryRequest(google.protobuf.message.Message):
    """Define which data we want"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    VIEW_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    path: builtins.str
    view: types_pb2.View.ValueType
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[types_pb2.Field.ValueType]: ...
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        view: types_pb2.View.ValueType = ...,
        fields: collections.abc.Iterable[types_pb2.Field.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields", b"fields", "path", b"path", "view", b"view"]) -> None: ...

global___EntryRequest = EntryRequest

class GetRequest(google.protobuf.message.Message):
    """Request a set of entries."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntryRequest]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___EntryRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___GetRequest = GetRequest

class GetResponse(google.protobuf.message.Message):
    """Global errors are specified in `error`.
    Errors for individual entries are specified in `errors`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[types_pb2.DataEntry]: ...
    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[types_pb2.DataEntryError]: ...
    @property
    def error(self) -> types_pb2.Error: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[types_pb2.DataEntry] | None = ...,
        errors: collections.abc.Iterable[types_pb2.DataEntryError] | None = ...,
        error: types_pb2.Error | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries", "error", b"error", "errors", b"errors"]) -> None: ...

global___GetResponse = GetResponse

class EntryUpdate(google.protobuf.message.Message):
    """Define the data we want to set"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRY_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def entry(self) -> types_pb2.DataEntry: ...
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[types_pb2.Field.ValueType]: ...
    def __init__(
        self,
        *,
        entry: types_pb2.DataEntry | None = ...,
        fields: collections.abc.Iterable[types_pb2.Field.ValueType] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["entry", b"entry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["entry", b"entry", "fields", b"fields"]) -> None: ...

global___EntryUpdate = EntryUpdate

class SetRequest(google.protobuf.message.Message):
    """A list of entries to be updated"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATES_FIELD_NUMBER: builtins.int
    @property
    def updates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntryUpdate]: ...
    def __init__(
        self,
        *,
        updates: collections.abc.Iterable[global___EntryUpdate] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["updates", b"updates"]) -> None: ...

global___SetRequest = SetRequest

class SetResponse(google.protobuf.message.Message):
    """Global errors are specified in `error`.
    Errors for individual entries are specified in `errors`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> types_pb2.Error: ...
    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[types_pb2.DataEntryError]: ...
    def __init__(
        self,
        *,
        error: types_pb2.Error | None = ...,
        errors: collections.abc.Iterable[types_pb2.DataEntryError] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error", b"error"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error", b"error", "errors", b"errors"]) -> None: ...

global___SetResponse = SetResponse

class SubscribeEntry(google.protobuf.message.Message):
    """Define what to subscribe to"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PATH_FIELD_NUMBER: builtins.int
    VIEW_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    path: builtins.str
    view: types_pb2.View.ValueType
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[types_pb2.Field.ValueType]: ...
    def __init__(
        self,
        *,
        path: builtins.str = ...,
        view: types_pb2.View.ValueType = ...,
        fields: collections.abc.Iterable[types_pb2.Field.ValueType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields", b"fields", "path", b"path", "view", b"view"]) -> None: ...

global___SubscribeEntry = SubscribeEntry

class SubscribeRequest(google.protobuf.message.Message):
    """Subscribe to changes in datapoints."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SubscribeEntry]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[global___SubscribeEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["entries", b"entries"]) -> None: ...

global___SubscribeRequest = SubscribeRequest

class SubscribeResponse(google.protobuf.message.Message):
    """A subscription response"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATES_FIELD_NUMBER: builtins.int
    @property
    def updates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntryUpdate]: ...
    def __init__(
        self,
        *,
        updates: collections.abc.Iterable[global___EntryUpdate] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["updates", b"updates"]) -> None: ...

global___SubscribeResponse = SubscribeResponse

class GetServerInfoRequest(google.protobuf.message.Message):
    """Nothing yet"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetServerInfoRequest = GetServerInfoRequest

class GetServerInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    version: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "version", b"version"]) -> None: ...

global___GetServerInfoResponse = GetServerInfoResponse
